#!/usr/bin/env bash
# gen-doc-status.sh — regenerate library/STATUS.md from library/manifest.toml
# and the content of every registered document.
#
# library/STATUS.md is GENERATED, never hand-edited (docs/program/12-
# documentation-program.md §2: "a date is not evidence of currency — a
# source revision is"). This script is the single source of truth for it,
# mirroring scripts/gen-progress.sh's shape: plain bash + standard tools,
# a --check mode for CI idempotency, no new dependencies.
#
# Why a content hash, not `git rev-parse HEAD` (librarian QA finding 1,
# thr_74hvpkqnxjp9q): a git-HEAD anchor is self-referential for the very
# commit that introduces STATUS.md — you must generate it BEFORE that
# commit exists, so the embedded HEAD is always the *parent* commit, and
# checking out the finished commit and regenerating disagrees with what
# got committed. A hash of the manifest plus every non-status registered
# document's bytes has no such cycle: it is a pure function of tree
# content, well-defined at generation time and reproducible byte-for-byte
# by anyone who checks out that tree, matching Ken's own content-
# addressing principle (`spec/00-overview.md` glossary: "Content-addressed
# — identified by the hash of structure").
#
# Usage: scripts/gen-doc-status.sh [--check]
#   (no args)  regenerate library/STATUS.md in place.
#   --check    write to a temp file and diff against the committed file;
#              exit non-zero if they differ (AC3: unchanged tree -> no-op).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MANIFEST="$REPO_ROOT/library/manifest.toml"
OUT_FILE="$REPO_ROOT/library/STATUS.md"

MODE="${1:-write}"
if [ "$MODE" = "--check" ]; then
  MODE="check"
fi

if [ ! -f "$MANIFEST" ]; then
  echo "gen-doc-status: manifest not found: $MANIFEST" >&2
  exit 1
fi

# --- manifest parsing -----------------------------------------------------
# library/manifest.toml is a small, hand-controlled TOML subset: a run of
# `[[document]]` tables, each with flat `key = "value"` scalar fields. This
# single-pass awk parser depends on that shape, not on general TOML — it is
# not meant to read arbitrary TOML.

TMP_TABLE="$(mktemp)"
HASH_INPUT="$(mktemp)"
TMP_OUT="$(mktemp)"
trap 'rm -f "$TMP_TABLE" "$HASH_INPUT" "$TMP_OUT"' EXIT

awk '
  function field(line,  v) {
    v = line
    sub(/^[a-z]+[[:space:]]*=[[:space:]]*"/, "", v)
    sub(/".*/, "", v)
    return v
  }
  /^\[\[document\]\]/ {
    if (path != "") print path "\t" kind "\t" authority "\t" availability
    path = ""; kind = ""; authority = ""; availability = ""
    next
  }
  /^path[[:space:]]*=/         { path = field($0) }
  /^kind[[:space:]]*=/         { kind = field($0) }
  /^authority[[:space:]]*=/    { authority = field($0) }
  /^availability[[:space:]]*=/ { availability = field($0) }
  END { if (path != "") print path "\t" kind "\t" authority "\t" availability }
' "$MANIFEST" > "$TMP_TABLE"

ROWS=""
COUNT=0
cat "$MANIFEST" >> "$HASH_INPUT"

while IFS=$'\t' read -r path kind authority availability; do
  [ -z "$path" ] && continue
  COUNT=$((COUNT + 1))
  ROWS="${ROWS}| \`${path}\` | ${kind} | ${authority} | ${availability} |
"
  # Every registered document's own bytes feed the hash EXCEPT the status
  # page itself — STATUS.md hashing its own about-to-be-written content
  # would be exactly the self-reference this design avoids.
  if [ "$kind" != "status" ]; then
    cat "$REPO_ROOT/$path" >> "$HASH_INPUT"
  fi
done < "$TMP_TABLE"

CONTENT_HASH="$(sha256sum "$HASH_INPUT" | cut -c1-16)"

# --- render -----------------------------------------------------------

render() {
  cat <<EOF
# Library status

**Generated by \`scripts/gen-doc-status.sh\` — do not hand-edit.** Currency
is this file's one job: it is anchored to a content revision, never a
typed date (docs/program/12-documentation-program.md §2).

**Content revision:** \`${CONTENT_HASH}\` — a hash of \`manifest.toml\` plus
every registered non-status document's bytes. Content-addressed rather
than a git commit SHA: a git-HEAD anchor is self-referential for the
commit that introduces this very file. Re-running the generator against
an unchanged tree reproduces this hash byte-for-byte (AC3).

## Registered documents

Every row below is one \`[[document]]\` entry in \`library/manifest.toml\`.
A document with no row here has no manifest entry and fails gate 1.

| Path | Kind | Authority | Availability |
|---|---|---|---|
${ROWS}
**Total:** ${COUNT} registered document(s).

## Regenerating

\`\`\`
scripts/gen-doc-status.sh          # regenerate in place
scripts/gen-doc-status.sh --check  # verify committed file is current (CI)
\`\`\`
EOF
}

if [ "$MODE" = "check" ]; then
  render > "$TMP_OUT"
  if ! diff -u "$OUT_FILE" "$TMP_OUT"; then
    echo "gen-doc-status --check: library/STATUS.md is stale — run scripts/gen-doc-status.sh" >&2
    exit 1
  fi
  echo "gen-doc-status --check: library/STATUS.md is current."
else
  render > "$OUT_FILE"
  echo "gen-doc-status: wrote $OUT_FILE"
fi
